server:
  port: 8003
#mybatis配置
mybatis:
  type-aliases-package: com.bjpowernode.springcloud.pojo
  config-location: classpath:mybatis/mybatis-confg.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db03?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
#Eureka配置  服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-privoder-dept-8003  #修改Eureka的描述信息
#info配置
#让别人看到
info:
  app.name: kuangshen-springcloud
  company.name: blog.zhangstudy.com





